name: pokedex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/types/bug.png
    - assets/types/dark.png
    - assets/types/dragon.png
    - assets/types/electric.png
    - assets/types/fairy.png
    - assets/types/fighting.png
    - assets/types/fire.png
    - assets/types/flying.png
    - assets/types/ghost.png
    - assets/types/grass.png
    - assets/types/ground.png
    - assets/types/ice.png
    - assets/types/normal.png
    - assets/types/poison.png
    - assets/types/psychic.png
    - assets/types/rock.png
    - assets/types/steel.png
    - assets/types/water.png